name: Build Dylib

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
      - name: Install ldid
        run: |
          brew install ldid
      - name: Compile
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker
          path: .theos/obj/debug/AutoClicker.dylib
